// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var app, config, db, exports, express, fs, modelsPath, mongoose, passport, path;

  express = require('express');

  path = require('path');

  fs = require('fs');

  mongoose = require('mongoose');

  process.env.NODE_ENV = process.env.NODE_ENV || 'development';

  config = require('./lib/config/config');

  db = mongoose.connect(config.mongo.uri, config.mongo.options);

  modelsPath = path.join(__dirname, 'lib/models');

  fs.readdirSync(modelsPath).forEach(function(file) {
    if (/(.*)\.(js$|coffee$)/.test(file)) {
      return require(modelsPath + "/" + file);
    }
  });

  passport = require('./lib/config/passport');

  app = express();

  require('./lib/config/express')(app);

  require('./lib/routes')(app);

  app.listen(config.port, function() {
    return console.log('Express server listening on port %d in %s mode', config.port, app.get('env'));
  });

  exports = module.exports = app;

}).call(this);

//# sourceMappingURL=server.map
