// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('bracketsApp').controller('LoginCtrl', function($scope, Auth, $location) {
    $scope.user = {};
    $scope.errors = {};
    $scope.login = function(form) {
      $scope.submitted = true;
      if (form.$valid) {
        Auth.login({
          email: $scope.user.email,
          password: $scope.user.password
        }).then(function() {
          return $location.path('/');
        })["catch"](function(err) {
          err = err.data;
          $scope.errors.other = err.message;
        });
        return;
      }
    };
  });

}).call(this);

//# sourceMappingURL=login.map
