// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('bracketsApp').controller('NavbarCtrl', function($scope, $location, Auth) {
    $scope.menu = [
      {
        title: 'Home',
        link: '/'
      }, {
        title: 'Settings',
        link: '/settings'
      }
    ];
    $scope.logout = function() {
      Auth.logout().then(function() {
        $location.path('/login');
      });
    };
    $scope.isActive = function(route) {
      return route === $location.path();
    };
  });

}).call(this);

//# sourceMappingURL=navbar.map
