// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var auth;

  module.exports = {
    auth: auth = function(req, res, next) {
      if (req.isAuthenticated()) {
        return next();
      }
      res.send(401);
    },
    setUserCookie: function(req, res, next) {
      if (req.user) {
        res.cookie('user', JSON.stringify(req.user.userInfo));
      }
      next();
    }
  };

}).call(this);

//# sourceMappingURL=middleware.map
