// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var api, index, middleware, passport, session, users;

  api = require('./controllers/api');

  index = require('./controllers');

  users = require('./controllers/users');

  passport = require('passport');

  session = require('./controllers/session');

  middleware = require('./middleware');

  module.exports = function(app) {
    app.get('/api/awesomeThings', api.awesomeThings);
    app.get('/api/getAllBrackets', api.getAllBrackets);
    app.get('/api/getBracketById/:id', api.getBracketById);
    app.post('/api/addBracket', api.addBracket);
    app.post('/api/updateBracket', api.updateBracket);
    app.del('/api/deleteBracket/:id', api.deleteBracket);
    app.post('/api/users', users.create);
    app.put('/api/users', users.changePassword);
    app.get('/api/users/me', users.me);
    app.get('/api/users/:id', users.show);
    app.post('/api/session', session.login);
    app.del('/api/session', session.logout);
    app.get('/api/*', function(req, res) {
      return res.send(404);
    });
    app.get('/partials/*', index.partials);
    return app.get('/*', middleware.setUserCookie, index.index);
  };

}).call(this);

//# sourceMappingURL=routes.map
