// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Bracket, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Bracket = mongoose.model('Bracket');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  exports.getAllBrackets = function(req, res) {
    return Bracket.find(function(err, brackets) {
      if (!err) {
        return res.json(brackets);
      } else {
        return res.send(err);
      }
    });
  };

  exports.getBracketById = function(req, res) {
    return Bracket.findById(req.params.id, function(err, bracket) {
      if (!err) {
        return res.json(bracket);
      } else {
        return res.send(err);
      }
    });
  };

  exports.addBracket = function(req, res) {
    Bracket.create({
      name: req.body.name,
      createdBy: req.body.user.email,
      bracket: JSON.stringify({
        teams: [["Team 1", "Team 2"], ["Team 3", "Team 4"]],
        results: []
      })
    }, function(err, bracket) {
      return res.json(bracket);
    });
  };

  exports.updateBracket = function(req, res) {
    Bracket.findById(req.body.id, function(err, bracket) {
      if (!err) {
        bracket.bracket = req.body.bracket;
        bracket.save();
        return res.json(bracket);
      } else {
        return res.send(err);
      }
    });
  };

  exports.deleteBracket = function(req, res) {
    Bracket.findByIdAndRemove(req.body.id, function(err) {
      if (!err) {
        return res.json(req.body.id);
      } else {
        return res.send(err);
      }
    });
  };

}).call(this);

//# sourceMappingURL=api.map
