// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var path;

  path = require('path');

  exports.partials = function(req, res) {
    var requestedView, stripped;
    stripped = req.url.split('.')[0];
    requestedView = path.join('./', stripped);
    res.render(requestedView, function(err, html) {
      if (err) {
        res.status(404);
        res.send(404);
      } else {
        res.send(html);
      }
    });
  };

  exports.index = function(req, res) {
    res.render('index');
  };

}).call(this);

//# sourceMappingURL=index.map
