// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var mongoose, passport;

  mongoose = require('mongoose');

  passport = require('passport');

  exports.logout = function(req, res) {
    req.logout();
    res.send(200);
  };

  exports.login = function(req, res, next) {
    passport.authenticate('local', function(err, user, info) {
      var error;
      error = err || info;
      if (error) {
        return res.json(401, error);
      }
      req.logIn(user, function(err) {
        if (err) {
          return res.send(err);
        }
        res.json(req.user.userInfo);
      });
    })(req, res, next);
  };

}).call(this);

//# sourceMappingURL=session.map
