// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var User, mongoose, passport;

  mongoose = require('mongoose');

  User = mongoose.model('User');

  passport = require('passport');

  exports.create = function(req, res, next) {
    var newUser;
    newUser = new User(req.body);
    newUser.provider = 'local';
    newUser.save(function(err) {
      if (err) {
        return res.json(400, err);
      }
      return req.logIn(newUser, function(err) {
        if (err) {
          return next(err);
        }
        return res.json(req.user.userInfo);
      });
    });
  };

  exports.show = function(req, res, next) {
    var userId;
    userId = req.params.id;
    User.findById(userId, function(err, user) {
      if (err) {
        return next(err);
      }
      if (!user) {
        return res.send(404);
      }
      return res.send({
        profile: user.profile
      });
    });
  };

  exports.changePassword = function(req, res, next) {
    var newPass, oldPass, userId;
    userId = req.user._id;
    oldPass = String(req.body.oldPassword);
    newPass = String(req.body.newPassword);
    return User.findById(userId, function(err, user) {
      if (user.authenticate(oldPass)) {
        user.password = newPass;
        user.save(function(err) {
          if (err) {
            return res.send(400);
          }
          res.send(200);
        });
      } else {
        res.send(403);
      }
    });
  };

  exports.me = function(req, res) {
    return res.json(req.user || null);
  };

}).call(this);

//# sourceMappingURL=users.map
