// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var _;

  _ = require("lodash");


  /*
  Load environment configuration
   */

  module.exports = _.merge(require("./env/all.js"), require("./env/" + process.env.NODE_ENV + ".js") || {});

}).call(this);

//# sourceMappingURL=config.map
