// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var Bracket, User, mongoose;

  mongoose = require('mongoose');

  User = mongoose.model('User');

  Bracket = mongoose.model('Bracket');

}).call(this);

//# sourceMappingURL=dummydata.map
