// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var path, rootPath;

  path = require('path');

  rootPath = path.normalize(__dirname + '/../../..');

  module.exports = {
    root: rootPath,
    port: process.env.PORT || 3000,
    mongo: {
      options: {
        db: {
          safe: true
        }
      }
    }
  };

}).call(this);

//# sourceMappingURL=all.map
