// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  module.exports = {
    env: 'development',
    mongo: {
      uri: 'mongodb://localhost/brackets-dev'
    }
  };

}).call(this);

//# sourceMappingURL=development.map
