// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  module.exports = {
    env: 'production',
    mongo: {
      uri: process.env.MONGOHQ_URL
    }
  };

}).call(this);

//# sourceMappingURL=production.map
