// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  module.exports = {
    env: 'test',
    mongo: {
      uri: 'mongodb://localhost/brackets-test'
    }
  };

}).call(this);

//# sourceMappingURL=test.map
