// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module('bracketsApp').factory("Session", function($resource) {
    return $resource('/api/session/');
  });

}).call(this);

//# sourceMappingURL=session.map
